apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: exercicio-kube
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"